### ISSUE TITLE
[1.12.2] Gaia III battle massive bug

### ISSUE THREAD

**Issue by CrosStarmont** [ExtraMeteorP/Extra-Botany#143]
WRITTEN WITH GOOGLE TRANSLATOR

Good morning, I've had a bug with the maid armor. When dying with it equipped against the gaia III, I was left with 0 hearts and in the middle of the death animation, I can not take damage, interact with blocks or interact with objects on the ground. I've tried using the "/kill" command, exiting and entering the game, changing game modes, changing dimensions, taking off my armor and nothing works, I literally can't play in that world anymore. I thought it was a bug caused by the "last chance" enchantment of the "openblocks" mod so I created another world, I didn't put that enchantment on my armor and apparently it worked, but now the bug happened to a friend on our server and He can no longer play (The only non-vanilla enchantment he has is the "Soul Bound" enchantment from the "open blocks" mod) Is there a way to prevent this from happening or fix it without having to make a backup? Thanks in advance and sorry for the spelling mistakes. 

In addition, say that we play on 1.12.2 and we have a modpack with 57 mods

**Comment by IvanG343** [comment]
It happens when you wear at least Shadow Pleiades Combat Maid set and the Mana Ring or Mana Tablet. On version **ExtraBotany-r1.1-60-beta-hotfix.jar** you will stuck in death animation loop, on version 1.1-59 game crashes with the following exception:
java.lang.NoSuchMethodError: com.meteor.extrabotany.api.ExtraBotanyAPI.dealTrueDamage(Lnet/minecraft/entity/EntityLivingBase;Lnet/minecraft/entity/EntityLivingBase;F)Z
	at com.meteor.extrabotany.common.entity.gaia.EntitySkullMissile.func_70071_h_(EntitySkullMissile.java:184)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


This issue not happens when you fight in Terrasteel Armor set or Pleiades Combat Maid without Mana Ring or Mana Tablet

**Comment by ufoluv** [comment]
does the bug happen if you have a sphere of nature? it works kinda same way as rings of mana
