### ISSUE TITLE
[Crash] Gaia III is accessing client only classes on server

### ISSUE THREAD

**Issue by zlainsama** [ExtraMeteorP/Extra-Botany#44]
`java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at com.meteor.extrabotany.common.entity.gaia.EntityGaiaIII.func_70636_d(EntityGaiaIII.java:296)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 13 more
Caused by: java.lang.NullPointerException`

Version:  r1.1-53-fixed
Full crash report: https://pastebin.com/faCVA6Lw

Hard crash, the server still crashes when restarting.

**Comment by zlainsama** [comment]
盖亚3尝试在服务器上访问客户端专有类
看源码，是在获取本地化的盖亚3的实体名称
你应当确保实际的本地化只发生在客户端上

**Comment by ExtraMeteorP** [comment]
是大佬
不知道大佬有没有什么比较好的办法测试这种sideonly问题，还是说只能自己开服测

**Comment by zlainsama** [comment]
不是大佬，我都没写过几个大点的内容mod
我是基本手动测一遍变动过的内容，没问题就发布，反正有问题会有人来报告

**Comment by ExtraMeteorP** [comment]
修好了
