### ISSUE TITLE
[Crash] NPE during Void Herrscher fight

### ISSUE THREAD

**Issue by zlainsama** [ExtraMeteorP/Extra-Botany#47]
`java.lang.NullPointerException: Ticking entity
	at com.meteor.extrabotany.common.entity.gaia.EntityVoidHerrscher.disarm(EntityVoidHerrscher.java:467)
	at com.meteor.extrabotany.common.entity.gaia.EntityVoidHerrscher.func_70636_d(EntityVoidHerrscher.java:356)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)`

Version: r1.1-53-fix
Full crash report: https://pastebin.com/eFNFHW4F

This happens when a player dies during the fight, and when they came back to the fighting area with empty inventory.

**Comment by ExtraMeteorP** [comment]
umm 要等我五月考完第一门了
