### ISSUE TITLE
Stackoverflowerror causes the server to crash

### ISSUE THREAD

**Issue by ViosinDeng** [ExtraMeteorP/Extra-Botany#88]
```

[22:43:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingHealEvent@2497ac60:
java.lang.StackOverflowError: null
	at java.util.zip.ZipCoder.getBytes(ZipCoder.java:86) ~[?:1.8.0_231]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:316) ~[?:1.8.0_231]
	at java.util.jar.JarFile.getEntry(JarFile.java:240) ~[?:1.8.0_231]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223) ~[?:1.8.0_231]
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1054) ~[?:1.8.0_231]
	at sun.misc.URLClassPath.getResource(URLClassPath.java:249) ~[?:1.8.0_231]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[?:1.8.0_231]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_231]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_231]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_231]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_231]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_231]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_231]
	at org.apache.logging.log4j.util.LoaderUtil.loadClass(LoaderUtil.java:141) ~[log4j-api-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.loadClass(ThrowableProxy.java:549) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.toExtendedStackTrace(ThrowableProxy.java:661) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:138) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.impl.ThrowableProxy.<init>(ThrowableProxy.java:122) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.impl.MutableLogEvent.getThrownProxy(MutableLogEvent.java:338) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.pattern.ExtendedThrowablePatternConverter.format(ExtendedThrowablePatternConverter.java:61) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.pattern.PatternFormatter.format(PatternFormatter.java:38) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:333) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.layout.PatternLayout$PatternSerializer.toSerializable(PatternLayout.java:323) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:208) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.layout.PatternLayout.toSerializable(PatternLayout.java:57) ~[log4j-core-2.8.1.jar:2.8.1]
	at com.mojang.util.QueueLogAppender.append(QueueLogAppender.java:39) ~[authlib-1.5.25.jar:?]
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146) ~[log4j-core-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2091) ~[log4j-api-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2011) ~[log4j-api-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884) ~[log4j-api-2.8.1.jar:2.8.1]
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:854) ~[log4j-api-2.8.1.jar:2.8.1]
	at net.minecraftforge.fml.common.eventhandler.EventBus.handleException(EventBus.java:212) ~[EventBus.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:196) ~[EventBus.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:631) ~[ForgeHooks.class:git-CatServer-1.12.2-b19657a]
	at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1603) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(EntityPlayer.java:1193) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1053) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1087) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:816) ~[oq.class:?]
	at com.meteor.extrabotany.common.brew.potion.PotionHealReverse.onUpdate(PotionHealReverse.java:27) ~[PotionHealReverse.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_551_PotionHealReverse_onUpdate_LivingHealEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:191) ~[EventBus.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.event.ForgeEventFactory.onLivingHeal(ForgeEventFactory.java:577) ~[ForgeEventFactory.class:git-CatServer-1.12.2-b19657a]
	at net.minecraft.entity.EntityLivingBase.heal(EntityLivingBase.java:931) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70691_i(EntityLivingBase.java:927) ~[vp.class:?]
	at com.meteor.extrabotany.common.item.equipment.armor.combatmaid.ItemCombatMaidHelm.onEntityAttacked(ItemCombatMaidHelm.java:102) ~[ItemCombatMaidHelm.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_536_ItemCombatMaidHelm_onEntityAttacked_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:191) ~[EventBus.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:631) ~[ForgeHooks.class:git-CatServer-1.12.2-b19657a]
	at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1603) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(EntityPlayer.java:1193) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1053) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1087) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:816) ~[oq.class:?]
	at com.meteor.extrabotany.common.brew.potion.PotionHealReverse.onUpdate(PotionHealReverse.java:27) ~[PotionHealReverse.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_551_PotionHealReverse_onUpdate_LivingHealEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:191) ~[EventBus.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.event.ForgeEventFactory.onLivingHeal(ForgeEventFactory.java:577) ~[ForgeEventFactory.class:git-CatServer-1.12.2-b19657a]
	at net.minecraft.entity.EntityLivingBase.heal(EntityLivingBase.java:931) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70691_i(EntityLivingBase.java:927) ~[vp.class:?]
	at com.meteor.extrabotany.common.item.equipment.armor.combatmaid.ItemCombatMaidHelm.onEntityAttacked(ItemCombatMaidHelm.java:102) ~[ItemCombatMaidHelm.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_536_ItemCombatMaidHelm_onEntityAttacked_LivingHurtEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:191) ~[EventBus.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.common.ForgeHooks.onLivingHurt(ForgeHooks.java:631) ~[ForgeHooks.class:git-CatServer-1.12.2-b19657a]
	at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1603) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(EntityPlayer.java:1193) ~[aed.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:1053) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1087) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:816) ~[oq.class:?]
	at com.meteor.extrabotany.common.brew.potion.PotionHealReverse.onUpdate(PotionHealReverse.java:27) ~[PotionHealReverse.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_551_PotionHealReverse_onUpdate_LivingHealEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:191) ~[EventBus.class:git-CatServer-1.12.2-b19657a]
	at net.minecraftforge.event.ForgeEventFactory.onLivingHeal(ForgeEventFactory.java:577) ~[ForgeEventFactory.class:git-CatServer-1.12.2-b19657a]
	at net.minecraft.entity.EntityLivingBase.heal(EntityLivingBase.java:931) ~[vp.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70691_i(EntityLivingBase.java:927) ~[vp.class:?]
	at com.meteor.extrabotany.common.item.equipment.armor.combatmaid.ItemCombatMaidHelm.onEntityAttacked(ItemCombatMaidHelm.java:102) ~[ItemCombatMaidHelm.class:?]
```
When a player uses magic finger to attack another player wearing combat mail helm, the server will crash
I am not very good at English. Please forgive me if you are offended
These sentences are obtained by translation tools.

**Comment by ExtraMeteorP** [comment]
那就说中文呗 了解了

**Comment by ExtraMeteorP** [comment]
update
