### ISSUE TITLE
服务器后台报错，触发原因不明

### ISSUE THREAD

**Issue by EnterFor** [ExtraMeteorP/Extra-Botany#89]
服务端为CatServer最新的稳定版
错误内容：
`[23:18:47] [Server thread/FATAL]: Error executing task 
java.util.concurrent.ExecutionException: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to com.meteor.extrabotany.common.item.lens.ItemLens
at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_211]
at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_211]
at net.minecraft.util.Util.func_181617_a(Util.java:51) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:841) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to com.meteor.extrabotany.common.item.lens.ItemLens
at com.meteor.extrabotany.common.crafting.recipe.brew.PotionLensRecipe.func_77572_b(PotionLensRecipe.java:62) ~[PotionLensRecipe.class:?]
at net.minecraft.inventory.Container.func_192389_a(Container.java:949) ~[afr.class:?]
at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:99) ~[agi.class:?]
at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:146) ~[afy.class:?]
at net.minecraft.inventory.Slot.func_75215_d(Slot.java:70) ~[agr.class:?]
at net.minecraft.inventory.Container.func_184996_a(Container.java:423) ~[afr.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2121) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:38) ~[lf.class:?]
at net.minecraft.network.play.client.CPacketClickWindow.func_148833_a(CPacketClickWindow.java:12) ~[lf.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
at net.minecraft.util.Util.func_181617_a(Util.java:50) ~[h.class:?]`

**Comment by ExtraMeteorP** [comment]
update
